# Generated by Django 5.2.3 on 2025-06-28 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bioData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.BigIntegerField()),
                ('name', models.CharField(max_length=20)),
                ('dob', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('linkdin', models.URLField()),
                ('contact', models.CharField(max_length=15)),
                ('gitlink', models.URLField()),
                ('leetcodelink', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='exp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.BigIntegerField()),
                ('title', models.CharField()),
                ('desc', models.TextField()),
                ('cred', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.URLField()),
                ('prjurl', models.URLField()),
                ('title', models.CharField()),
            ],
        ),
    ]
