# Generated by Django 5.2.3 on 2025-06-29 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='biodata',
            name='istrue',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='biodata',
            name='role',
            field=models.CharField(default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='exp',
            name='role',
            field=models.CharField(default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='role',
            field=models.CharField(default='none', max_length=20),
        ),
    ]
